app:
  image: ruby:2.3.0
  command: ./bin/start
  working_dir: /usr/src/app
  environment:
    BUNDLE_PATH: /usr/src/app/.bundle
  volumes:
    - .:/usr/src/app
  ports:
    - "4000:4000"

nginx:
  build: .
  volumes:
    - ./output:/var/www/
    - ./sites-enabled:/etc/nginx/sites-enabled
  ports:
   - "80:80"
  environment:
   - NGINX_HOST=quintadaricafe.pt
   - NGINX_PORT=80